
version: "3.9"
services:
  jammy:
    container_name: jammy
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /home/general_user
    restart: "no"
    tty: true #この行がないとコンテナに入れない。
    networks:
      ubuntu_network:
        ipv4_address: 172.20.0.2
networks:
  ubuntu_network:
    name: ubuntu_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1